"""fix column name typo

Revision ID: 200074d858e4
Revises: d5ffb2c6f8a1
Create Date: 2025-10-21 22:03:44.268267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200074d858e4'
down_revision: Union[str, None] = 'd5ffb2c6f8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.String(length=300), nullable=True))
    op.drop_column('tasks', 'describtion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('describtion', sa.VARCHAR(length=300), nullable=True))
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
