"""added users relationship to tasks

Revision ID: 7f784e8d6fde
Revises: 024a8d5c6a89
Create Date: 2025-10-22 18:51:58.741264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f784e8d6fde'
down_revision: Union[str, None] = '024a8d5c6a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_user_tasks", 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_tasks", type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
